### ISSUE TITLE
Incorrect steel bar price

### ISSUE THREAD

**Issue by bobyto93** [ClutchMasterFTW/Monolith-Crafting-Calculator#4]
Steel bars no longer require 3 iron bars to be crafted, it now requires only 2 iron bars to make a steel bar, all the crafting  recipies need to  be adjusted.

![image](https://user-images.githubusercontent.com/109415842/179351017-32f4b88a-7667-4c09-a714-6047582bb6cf.png)
![image](https://user-images.githubusercontent.com/109415842/179351025-cd4c6936-6e6e-46cb-b0ae-3db9d58c1048.png)
![image](https://user-images.githubusercontent.com/109415842/179351127-0e802ace-6b91-4d82-b7e7-c0a85f0954c5.png)

EG. AUG requires 48 iron bars instead of the 64 indicated for the crafting of the steel bars and the in turn the gun

**Comment by KyleR357** [comment]
Thank you for the heads up! This issue will be resolved in the next update, following other big additions.

**Comment by KyleR357** [comment]
Fixed.
