### ISSUE TITLE
Incorrect value of  stack sizes

### ISSUE THREAD

**Issue by bobyto93** [ClutchMasterFTW/Monolith-Crafting-Calculator#9]
The values for stack sizes are not correct if the option "Stacks:ON" is selected for titanium (both bars and ores) and  all the logs and planks

![image](https://user-images.githubusercontent.com/109415842/185769878-c102f96b-c1b9-4647-9b47-f72fe7da6a47.png)
![image](https://user-images.githubusercontent.com/109415842/185769898-e96ac886-da8c-4392-a199-62e421af5295.png)

In all cases the values go to 128 per stack when the correct values are:
titanium ore - 64
titanium bar -32
logs -200
planks -200

I am assuming there is a limitation for both planks and logs so their values can't exceed 128, but titanium ore and bar values should be changable

**Comment by KyleR357** [comment]
Thank you, I noticed this bug in the past though I totally forgot about it. Thank you for bringing it back up, it will be fixed in the next major update.

**Comment by KyleR357** [comment]
Fixed in Version 2.3. Thanks 👍🏼
